# Generated by Django 5.0.6 on 2024-05-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
